# Generated by Django 4.2.22 on 2025-10-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('tag_id', models.CharField(max_length=64, unique=True, verbose_name='标签id')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('build_in', models.BooleanField(default=False, verbose_name='是否内置')),
            ],
            options={
                'verbose_name': '数据源标签',
                'db_table': 'operation_analysis_data_source_tag',
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=128, verbose_name='目录名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_directories', to='operation_analysis.directory', verbose_name='父目录')),
            ],
            options={
                'verbose_name': '目录',
                'db_table': 'operation_analysis_directory',
            },
        ),
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='命名空间名称')),
                ('account', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('domain', models.CharField(max_length=255, verbose_name='域名')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '命名空间',
                'db_table': 'operation_analysis_namespace',
            },
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='拓扑图名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('other', models.JSONField(blank=True, help_text='拓扑图其他配置', null=True)),
                ('view_sets', models.JSONField(default=list, help_text='拓扑图视图集配置')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology', to='operation_analysis.directory', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '拓扑图',
                'db_table': 'operation_analysis_topology',
            },
        ),
        migrations.CreateModel(
            name='DataSourceAPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=255, verbose_name='数据源名称')),
                ('rest_api', models.CharField(max_length=255, verbose_name='REST API URL')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('params', models.JSONField(blank=True, help_text='API请求参数', null=True, verbose_name='请求参数')),
                ('chart_type', models.JSONField(blank=True, default=list, help_text='图表类型', null=True)),
                ('namespaces', models.ManyToManyField(blank=True, help_text='会话关联的事件', related_name='data_sources', to='operation_analysis.namespace', verbose_name='命名空间')),
                ('tag', models.ManyToManyField(blank=True, help_text='数据源标签', related_name='data_sources', to='operation_analysis.datasourcetag')),
            ],
            options={
                'verbose_name': '数据源API',
                'db_table': 'operation_analysis_data_source_api',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='仪表盘名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('filters', models.JSONField(blank=True, help_text='仪表盘公共过滤条件', null=True, verbose_name='过滤条件')),
                ('other', models.JSONField(blank=True, help_text='仪表盘其他配置', null=True, verbose_name='其他配置')),
                ('view_sets', models.JSONField(default=list, help_text='仪表盘视图集配置', verbose_name='视图集配置')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='operation_analysis.directory', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '仪表盘',
                'db_table': 'operation_analysis_dashboard',
            },
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='架构图名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('other', models.JSONField(blank=True, help_text='架构图其他配置', null=True)),
                ('view_sets', models.JSONField(default=list, help_text='架构图视图集配置')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architecture', to='operation_analysis.directory', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '架构图',
                'db_table': 'operation_analysis_architecture',
            },
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent'),
        ),
        migrations.AddConstraint(
            model_name='datasourceapimodel',
            constraint=models.UniqueConstraint(fields=('name', 'rest_api'), name='unique_name_rest_api'),
        ),
    ]
