# Generated by Django 4.2.7 on 2025-11-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0008_architecture"),
    ]

    operations = [
        migrations.AddField(model_name="architecture", name="groups", field=models.JSONField(blank=True, default=list, help_text="组织", null=True),),
        migrations.AddField(model_name="dashboard", name="groups", field=models.JSONField(blank=True, default=list, help_text="组织", null=True),),
        migrations.AddField(
            model_name="datasourceapimodel", name="groups", field=models.JSONField(blank=True, default=list, help_text="组织", null=True),
        ),
        migrations.AddField(model_name="directory", name="groups", field=models.JSONField(blank=True, default=list, help_text="组织", null=True),),
        migrations.AddField(model_name="namespace", name="groups", field=models.JSONField(blank=True, default=list, help_text="组织", null=True),),
        migrations.AddField(model_name="topology", name="groups", field=models.JSONField(blank=True, default=list, help_text="组织", null=True),),
    ]
