# Generated by Django 4.2.7 on 2025-11-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0009_architecture_groups_dashboard_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="namespace", name="groups",),
    ]
