# Generated by Django 4.2.7 on 2025-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operation_analysis", "0010_remove_namespace_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="namespace",
            field=models.CharField(default="bklite", help_text="NATS服务端的命名空间,用于消息主题前缀", max_length=64, verbose_name="NATS命名空间"),
        ),
        migrations.AddField(
            model_name="namespace",
            name="enable_tls",
            field=models.BooleanField(default=False, help_text="是否使用TLS安全连接(tls://)", verbose_name="启用TLS"),
        )
    ]
