# Generated by Django 4.2.7 on 2026-01-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0007_aggregationrules_strategy_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmStrategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(help_text="策略名称", max_length=100)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[("smart_denoise", "智能降噪"), ("missing_detection", "缺失检测")], default="smart_denoise", help_text="策略类型", max_length=32
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                ("description", models.TextField(blank=True, help_text="策略描述", null=True)),
                ("team", models.JSONField(default=list, help_text="关联组织")),
                ("dispatch_team", models.JSONField(default=list, help_text="分派组织")),
                ("match_rules", models.JSONField(default=list, help_text="匹配规则")),
                ("params", models.JSONField(default=dict, help_text="策略参数")),
                ("auto_close", models.BooleanField(default=True, help_text="是否自动关闭告警")),
                ("close_minutes", models.IntegerField(default=120, help_text="自动关闭时间(分钟)")),
            ],
            options={
                "verbose_name": "告警策略",
                "verbose_name_plural": "告警策略",
                "db_table": "alerts_alarm_strategy",
                "unique_together": {("name", "strategy_type")},
            },
        ),
        migrations.AddField(
            model_name="alert", name="group_by_field", field=models.CharField(blank=True, help_text="聚合字段", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="alert", name="is_session_alert", field=models.BooleanField(db_index=True, default=False, help_text="是否为会话窗口Alert"),
        ),
        migrations.AddField(model_name="alert", name="session_end_time", field=models.DateTimeField(blank=True, help_text="会话结束时间", null=True),),
        migrations.AddField(
            model_name="alert",
            name="session_status",
            field=models.CharField(
                blank=True,
                choices=[("observing", "观察中"), ("confirmed", "已确认"), ("recovered", "已恢复")],
                db_index=True,
                help_text="会话Alert状态",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event", name="event_type", field=models.SmallIntegerField(choices=[(0, "告警事件"), (1, "恢复事件")], default=0, help_text="发生类型"),
        ),
        migrations.AddField(model_name="event", name="location", field=models.CharField(blank=True, help_text="事件发生位置", max_length=200, null=True),),
        migrations.AddField(model_name="event", name="service", field=models.CharField(blank=True, help_text="所属服务", max_length=200, null=True),),
        migrations.AddField(model_name="event", name="tags", field=models.JSONField(default=dict, help_text="事件标签"),),
        migrations.AlterField(
            model_name="event",
            name="action",
            field=models.CharField(
                choices=[("created", "产生"), ("closed", "关闭"), ("recovery", "恢复")], default="created",
                help_text="事件动作", max_length=32
            ),
        ),
        migrations.AddField(model_name="alert", name="team", field=models.JSONField(default=list, help_text="关联组织"), ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待响应"),
                    ("processing", "处理中"),
                    ("resolved", "已处理"),
                    ("closed", "已关闭"),
                    ("unassigned", "未分派"),
                    ("auto_close", "自动关闭"),
                    ("auto_recovery", "自动恢复"),
                ],
                db_index=True,
                default="unassigned",
                help_text="告警状态",
                max_length=32,
            ),
        )
    ]
