# Generated by Django 4.2.7 on 2026-01-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0008_alarmstrategy_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="correlationrules", name="aggregation_rules",),
        migrations.AlterUniqueTogether(name="sessioneventrelation", unique_together=None,),
        migrations.RemoveField(model_name="sessioneventrelation", name="event",),
        migrations.RemoveField(model_name="sessioneventrelation", name="session",),
        migrations.RemoveField(model_name="sessionwindow", name="events",),
        migrations.DeleteModel(name="AggregationRules",),
        migrations.DeleteModel(name="CorrelationRules",),
        migrations.DeleteModel(name="SessionEventRelation",),
        migrations.DeleteModel(name="SessionWindow",),
    ]
