# Generated by Django 4.2.7 on 2026-03-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0010_remove_alert_alert_created_btree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmstrategy", name="last_execute_time", field=models.DateTimeField(blank=True, help_text="所有策略通用的最后执行时间", null=True),
        ),
    ]
