# Generated by Django 4.2.22 on 2025-10-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundAnomalyDetectionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('capability', models.IntegerField(verbose_name='能力演示ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('train_data', models.JSONField(help_text='训练数据，包含timestamp和value', verbose_name='文件数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '能力演示文件',
                'verbose_name_plural': '能力演示文件',
            },
        ),
        migrations.CreateModel(
            name='PlayGroundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='类别名称')),
                ('description', models.TextField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='playground.playgroundcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '体验应用类别',
                'verbose_name_plural': '体验应用类别',
            },
        ),
        migrations.CreateModel(
            name='PlayGroundCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('url', models.URLField(blank=True, help_text='能力的访问链接，可选', max_length=255, null=True, verbose_name='能力链接')),
                ('config', models.JSONField(blank=True, default=dict, help_text='能力的配置参数，存储为JSON格式', verbose_name='配置')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='playground.playgroundcategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '体验应用能力',
                'verbose_name_plural': '体验应用能力',
            },
        ),
    ]
