# Generated by Django 4.2.15 on 2025-11-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_monitorobjecttype_delete_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorplugin',
            name='collect_type',
            field=models.CharField(default='', max_length=50, verbose_name='采集类型'),
        ),
        migrations.AddField(
            model_name='monitorplugin',
            name='collector',
            field=models.CharField(default='', max_length=100, verbose_name='采集器名称'),
        ),
    ]
