# Generated by Django 4.2.27 on 2026-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_monitorpolicy_calculation_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpolicy',
            name='no_data_alert_name',
            field=models.CharField(default='', max_length=200, verbose_name='无数据告警名称'),
        ),
    ]
