# Generated by Django 4.2.15 on 2026-01-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_add_no_data_alert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoralert',
            name='dimensions',
            field=models.JSONField(default=dict, verbose_name='维度值'),
        ),
        migrations.AddField(
            model_name='monitoralert',
            name='metric_instance_id',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='指标实例ID'),
        ),
        migrations.AddField(
            model_name='monitorevent',
            name='dimensions',
            field=models.JSONField(default=dict, verbose_name='维度值'),
        ),
        migrations.AddField(
            model_name='monitorevent',
            name='metric_instance_id',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='指标实例ID'),
        ),
        migrations.CreateModel(
            name='PolicyInstanceBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('monitor_instance_id', models.CharField(db_index=True, max_length=100, verbose_name='监控实例ID')),
                ('metric_instance_id', models.CharField(max_length=255, verbose_name='指标实例ID')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorpolicy', verbose_name='监控策略')),
            ],
            options={
                'verbose_name': '策略实例基准',
                'verbose_name_plural': '策略实例基准',
                'unique_together': {('policy', 'metric_instance_id')},
            },
        ),
    ]
