# Generated by Django 4.2.27 on 2026-03-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_add_operation_logs_to_monitor_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=200, verbose_name='条件名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='条件描述')),
                ('condition', models.JSONField(default=dict, verbose_name='条件配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '监控条件',
                'verbose_name_plural': '监控条件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorConditionOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('organization', models.IntegerField(verbose_name='组织ID')),
                ('monitor_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='monitor.monitorcondition', verbose_name='监控条件')),
            ],
            options={
                'verbose_name': '监控条件组织',
                'verbose_name_plural': '监控条件组织',
                'unique_together': {('monitor_condition', 'organization')},
            },
        ),
    ]
