# Generated by Django 4.2.27 on 2026-03-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_add_monitor_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcondition',
            name='monitor_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorobject', verbose_name='监控对象'),
        ),
    ]
