# Generated by Django 4.2.22 on 2025-10-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0023_anomalydetectiontrainhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='数据集名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据集描述')),
            ],
            options={
                'verbose_name': '分类任务数据集',
                'verbose_name_plural': '分类任务数据集',
            },
        ),
        migrations.CreateModel(
            name='ClassificationTrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='训练数据名称')),
                ('train_data', models.JSONField(help_text='存储训练数据', verbose_name='训练数据')),
                ('metadata', models.JSONField(blank=True, help_text='训练数据元信息', null=True, verbose_name='元数据')),
                ('is_train_data', models.BooleanField(default=False, help_text='是否为训练数据', verbose_name='是否为训练数据')),
                ('is_val_data', models.BooleanField(default=False, help_text='是否为验证数据', verbose_name='是否为验证数据')),
                ('is_test_data', models.BooleanField(default=False, help_text='是否为测试数据', verbose_name='是否为测试数据')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_data', to='mlops.classificationdataset', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '分类任务训练数据',
                'verbose_name_plural': '分类任务训练数据',
            },
        ),
        migrations.CreateModel(
            name='ClassificationTrainJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待训练'), ('running', '训练中'), ('completed', '已完成'), ('failed', '训练失败')], default='pending', help_text='训练任务的当前状态', max_length=20, verbose_name='任务状态')),
                ('algorithm', models.CharField(choices=[('RandomForest', 'Random Forest'), ('XGBoost', 'XGBoost'), ('LogisticRegression', 'Logistic Regression'), ('SVM', 'Support Vector Machine'), ('NeuralNetwork', 'Neural Network')], help_text='使用的分类算法模型', max_length=50, verbose_name='算法模型')),
                ('hyperopt_config', models.JSONField(default=dict, help_text='用于超参数优化的配置参数', verbose_name='超参数优化配置')),
                ('max_evals', models.IntegerField(default=200, help_text='超参数优化的最大评估次数', verbose_name='最大评估次数')),
                ('test_data_id', models.ForeignKey(help_text='关联的分类测试数据集', on_delete=django.db.models.deletion.CASCADE, related_name='test_jobs', to='mlops.classificationtraindata', verbose_name='测试数据集')),
                ('train_data_id', models.ForeignKey(help_text='关联的分类训练数据集', on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.classificationtraindata', verbose_name='训练数据集')),
                ('val_data_id', models.ForeignKey(help_text='关联的分类验证数据集', on_delete=django.db.models.deletion.CASCADE, related_name='val_jobs', to='mlops.classificationtraindata', verbose_name='验证数据集')),
            ],
            options={
                'verbose_name': '分类任务训练作业',
                'verbose_name_plural': '分类任务训练作业',
            },
        ),
        migrations.CreateModel(
            name='ClassificationTrainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('algorithm', models.CharField(choices=[('RandomForest', 'Random Forest'), ('XGBoost', 'XGBoost'), ('LogisticRegression', 'Logistic Regression'), ('SVM', 'Support Vector Machine'), ('NeuralNetwork', 'Neural Network')], help_text='使用的分类算法模型', max_length=50, verbose_name='算法模型')),
                ('hyperopt_config', models.JSONField(default=dict, help_text='用于超参数优化的配置参数', verbose_name='超参数优化配置')),
                ('status', models.CharField(choices=[('pending', '待训练'), ('running', '训练中'), ('completed', '已完成'), ('failed', '训练失败')], default='pending', help_text='训练任务的当前状态', max_length=20, verbose_name='任务状态')),
                ('test_data_id', models.ForeignKey(help_text='关联的分类测试数据集', on_delete=django.db.models.deletion.CASCADE, related_name='test_history', to='mlops.classificationtraindata', verbose_name='测试数据集')),
                ('train_data_id', models.ForeignKey(help_text='关联的分类训练数据集', on_delete=django.db.models.deletion.CASCADE, related_name='train_history', to='mlops.classificationtraindata', verbose_name='训练数据集')),
                ('val_data_id', models.ForeignKey(help_text='关联的分类验证数据集', on_delete=django.db.models.deletion.CASCADE, related_name='val_history', to='mlops.classificationtraindata', verbose_name='验证数据集')),
            ],
            options={
                'verbose_name': '分类任务训练历史',
                'verbose_name_plural': '分类任务训练历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='服务的名称', max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(blank=True, help_text='服务的详细描述', null=True, verbose_name='服务描述')),
                ('model_version', models.CharField(default='latest', help_text='模型版本', max_length=50, verbose_name='模型版本')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='服务的当前状态', max_length=20, verbose_name='服务状态')),
                ('classification_train_job', models.ForeignKey(help_text='关联的分类训练任务模型ID', on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='mlops.classificationtrainjob', verbose_name='模型ID')),
            ],
            options={
                'verbose_name': '分类任务服务',
                'verbose_name_plural': '分类任务服务',
                'ordering': ['-created_at'],
            },
        ),
    ]
