# Generated by Django 4.2.22 on 2025-10-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0024_classificationdataset_classificationtraindata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationtrainjob',
            name='labels',
            field=models.JSONField(default=list, help_text='用户指定的用于训练的特征', verbose_name='训练特征'),
        ),
    ]
