# Generated by Django 4.2.22 on 2025-10-29 07:26

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0027_imageclassificationtraindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclassificationtraindata',
            name='image',
            field=models.ImageField(blank=True, help_text='上传到MinIO的图片', null=True, storage=django_minio_backend.models.MinioBackend(
                bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='训练图片'),
        ),
    ]
