# Generated by Django 4.2.22 on 2025-10-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0028_imageclassificationtraindata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageclassificationtraindata',
            old_name='image',
            new_name='images',
        ),
    ]
