# Generated by Django 4.2.22 on 2025-10-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0029_rename_image_imageclassificationtraindata_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageclassificationtraindata',
            name='images',
        ),
    ]
