# Generated by Django 4.2.27 on 2026-02-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0042_remove_rasaentity_dataset_remove_rasaform_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetectiontrainjob',
            name='algorithm',
            field=models.CharField(help_text='使用的异常检测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='classificationtrainjob',
            name='algorithm',
            field=models.CharField(help_text='使用的分类算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='imageclassificationtrainjob',
            name='algorithm',
            field=models.CharField(default='YOLOClassification', help_text='使用的YOLO分类算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='logclusteringtrainjob',
            name='algorithm',
            field=models.CharField(help_text='使用的日志聚类算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='objectdetectiontrainjob',
            name='algorithm',
            field=models.CharField(default='YOLODetection', help_text='使用的 YOLOv11 目标检测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainjob',
            name='algorithm',
            field=models.CharField(help_text='使用的时间序列预测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('algorithm_type', models.CharField(choices=[('anomaly_detection', '异常检测'), ('timeseries_predict', '时序预测'), ('log_clustering', '日志聚类'), ('classification', '文本分类'), ('image_classification', '图片分类'), ('object_detection', '目标检测')], db_index=True, help_text='算法所属的场景类型', max_length=50, verbose_name='算法类型')),
                ('name', models.CharField(help_text='算法的唯一标识，如 ECOD、IForest、XGBoost 等', max_length=100, verbose_name='算法标识')),
                ('display_name', models.CharField(help_text='在前端展示的算法名称', max_length=100, verbose_name='显示名称')),
                ('scenario_description', models.TextField(blank=True, default='', help_text='算法适用场景的描述说明', verbose_name='场景描述')),
                ('image', models.CharField(help_text='用于训练和推理的 Docker 镜像地址', max_length=255, verbose_name='Docker 镜像')),
                ('form_config', models.JSONField(blank=True, default=dict, help_text='前端动态表单的 JSON 配置，结构遵循 AlgorithmConfig 类型定义', verbose_name='表单配置')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='禁用后该算法将不在前端算法选择列表中显示', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '算法配置',
                'verbose_name_plural': '算法配置',
                'db_table': 'mlops_algorithm_config',
                'ordering': ['algorithm_type', 'id'],
                'unique_together': {('algorithm_type', 'name')},
            },
        ),
    ]
