# Generated by Django 4.2.27 on 2026-03-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0044_classificationserving_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectiondataset',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='anomalydetectionserving',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='anomalydetectiontrainjob',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='classificationdataset',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='classificationserving',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='classificationtrainjob',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='imageclassificationdataset',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='imageclassificationserving',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='imageclassificationtrainjob',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='logclusteringdataset',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='logclusteringserving',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='logclusteringtrainjob',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='objectdetectiondataset',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='objectdetectionserving',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='objectdetectiontrainjob',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='timeseriespredictdataset',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='timeseriespredictserving',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainjob',
            name='team',
            field=models.JSONField(default=list, help_text='关联的组织ID列表，用于权限控制', verbose_name='关联组织'),
        ),
    ]
