# Generated by Django 4.2.22 on 2025-11-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0031_delete_tokenconsumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltools",
            name="tools",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="WorkFlowConversationHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bot_id", models.IntegerField(db_index=True, verbose_name="机器人ID")),
                ("user_id", models.CharField(db_index=True, max_length=100, verbose_name="用户ID")),
                (
                    "conversation_role",
                    models.CharField(
                        choices=[("user", "用户"), ("bot", "机器人")],
                        db_index=True,
                        help_text="user: 用户输入, bot: 系统最终输出",
                        max_length=10,
                        verbose_name="对话角色",
                    ),
                ),
                ("conversation_content", models.TextField(verbose_name="对话内容")),
                ("conversation_time", models.DateTimeField(db_index=True, verbose_name="对话时间")),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("restful", "RESTful"),
                            ("celery", "Celery"),
                            ("enterprise_wechat", "Enterprise WeChat"),
                            ("wechat_official", "WeChat Official Account"),
                            ("dingtalk", "Ding Talk"),
                        ],
                        db_index=True,
                        default="restful",
                        help_text="对话入口类型：openai/restful/enterprise_wechat/wechat_official/dingtalk，celery定时触发不记录",
                        max_length=50,
                        verbose_name="入口类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkFlow对话历史",
                "verbose_name_plural": "WorkFlow对话历史",
                "db_table": "bot_mgmt_workflowconversationhistory",
                "ordering": ["-conversation_time"],
                "indexes": [
                    models.Index(fields=["bot_id", "-conversation_time"], name="bot_mgmt_wo_bot_id_68b0de_idx"),
                    models.Index(fields=["user_id", "-conversation_time"], name="bot_mgmt_wo_user_id_a5daaf_idx"),
                    models.Index(fields=["entry_type", "-conversation_time"], name="bot_mgmt_wo_entry_t_4eaed0_idx"),
                ],
            },
        ),
    ]
