# Generated by Django 4.2.22 on 2025-12-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0034_workflowconversationhistory_node_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(db_index=True, help_text="入口节点ID", max_length=100, verbose_name="节点ID")),
                (
                    "app_type",
                    models.CharField(choices=[("mobile", "移动端应用"), ("web_chat", "Web对话应用")], db_index=True, max_length=50, verbose_name="应用类型"),
                ),
                ("app_name", models.CharField(max_length=255, verbose_name="应用名称")),
                ("app_description", models.TextField(blank=True, default="", verbose_name="应用描述")),
                ("app_tags", models.JSONField(blank=True, default=list, help_text="仅mobile类型使用", verbose_name="应用标签")),
                ("app_icon", models.CharField(blank=True, default="", help_text="仅web_chat类型使用", max_length=100, verbose_name="应用图标")),
                ("node_config", models.JSONField(blank=True, default=dict, help_text="存储节点的完整配置参数", verbose_name="节点配置")),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chat_applications", to="opspilot.bot", verbose_name="机器人"
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天应用",
                "verbose_name_plural": "聊天应用",
                "db_table": "bot_mgmt_chatapplication",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["bot", "app_type"], name="bot_mgmt_ch_bot_id_2d9ae0_idx"),
                    # node_id 已在字段定义中通过 db_index=True 创建索引，
                    # 此处重复创建会导致达梦等数据库报错 CODE:-3236
                    # models.Index(fields=["node_id"], name="bot_mgmt_ch_node_id_448b49_idx"),
                ],
                "unique_together": {("bot", "node_id")},
            },
        ),
    ]
