# Generated by Django 4.2.22 on 2026-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0039_knowledgedocument_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否置顶"),
        ),
    ]
