# Generated by Django 4.2.22 on 2026-01-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0040_llmskill_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否置顶"),
        ),
    ]
