# Generated by Django 4.2.22 on 2026-02-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0043_alter_workflowconversationhistory_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowconversationhistory",
            name="execution_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=36, verbose_name="执行实例ID"),
        ),
        migrations.AddField(
            model_name="workflowtaskresult",
            name="execution_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=36, verbose_name="执行实例ID"),
        ),
        migrations.CreateModel(
            name="WorkFlowTaskNodeResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("execution_id", models.CharField(db_index=True, max_length=36, verbose_name="执行实例ID")),
                ("node_id", models.CharField(max_length=100, verbose_name="节点ID")),
                ("node_name", models.CharField(blank=True, default="", max_length=255, verbose_name="节点名称")),
                ("node_type", models.CharField(blank=True, default="", max_length=100, verbose_name="节点类型")),
                ("node_index", models.IntegerField(blank=True, null=True, verbose_name="节点执行顺序")),
                ("status", models.CharField(max_length=20, verbose_name="执行状态")),
                ("input_data", models.JSONField(default=dict, verbose_name="节点输入")),
                ("output_data", models.JSONField(default=dict, verbose_name="节点输出")),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("end_time", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("duration_ms", models.BigIntegerField(blank=True, null=True, verbose_name="耗时毫秒")),
                (
                    "task_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_results",
                        to="opspilot.workflowtaskresult",
                        verbose_name="执行主记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkFlow节点执行明细",
                "verbose_name_plural": "WorkFlow节点执行明细",
                "db_table": "bot_mgmt_workflowtasknoderesult",
                "indexes": [
                    models.Index(fields=["task_result", "node_index"], name="bot_mgmt_wo_task_re_2b5e3e_idx"),
                    models.Index(fields=["status", "end_time"], name="bot_mgmt_wo_status_6872ef_idx"),
                    models.Index(fields=["execution_id"], name="bot_mgmt_wo_executi_8b3bfd_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="workflowtasknoderesult",
            constraint=models.UniqueConstraint(fields=("execution_id", "node_id"), name="uniq_workflow_node_execution"),
        ),
    ]
