# Generated by Django 4.2.15 on 2025-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0012_sidecarapitoken_node_id_alter_sidecarapitoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='install_method',
            field=models.CharField(default='auto', max_length=50, verbose_name='安装方式'),
        ),
    ]
