# Generated by Django 4.2.15 on 2025-11-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0013_node_install_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
    ]
