# Generated by Django 4.2.15 on 2025-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0014_collector_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='package_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='包名称'),
        ),
    ]
