# Generated by Django 4.2.7 on 2026-01-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0011_fieldgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPersonalConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=255, verbose_name="用户名")),
                ("domain", models.CharField(db_index=True, max_length=255, verbose_name="域名")),
                ("config_key", models.CharField(db_index=True, help_text="配置类型标识，如: search_inst_{model_id}", max_length=100, verbose_name="配置键")),
                ("config_value", models.JSONField(default=dict, verbose_name="配置值")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "用户个人配置",
                "verbose_name_plural": "用户个人配置",
                "db_table": "cmdb_user_personal_config",
                "indexes": [
                    models.Index(fields=["username", "domain", "config_key"], name="cmdb_user_p_usernam_352081_idx"),
                    models.Index(fields=["username", "domain"], name="cmdb_user_p_usernam_82b846_idx"),
                ],
                "unique_together": {("username", "domain", "config_key")},
            },
        ),
    ]
