# Generated by Django 4.2.7 on 2026-03-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0013_publicenumlibrary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="规则名称")),
                ("organization", models.BigIntegerField(db_index=True, verbose_name="所属组织ID")),
                ("model_id", models.CharField(db_index=True, max_length=100, verbose_name="目标模型ID")),
                (
                    "filter_type",
                    models.CharField(choices=[("condition", "过滤条件"), ("instances", "实例选择")], default="instances", max_length=20, verbose_name="筛选类型"),
                ),
                ("instance_filter", models.JSONField(default=dict, verbose_name="实例筛选数据")),
                ("trigger_types", models.JSONField(default=list, verbose_name="触发类型列表")),
                ("trigger_config", models.JSONField(default=dict, verbose_name="触发条件配置")),
                ("recipients", models.JSONField(default=dict, verbose_name="接收对象")),
                ("channel_ids", models.JSONField(default=list, verbose_name="通知渠道ID列表")),
                ("is_enabled", models.BooleanField(db_index=True, default=True, verbose_name="启用状态")),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True, verbose_name="最近触发时间")),
                ("last_check_time", models.DateTimeField(blank=True, null=True, verbose_name="上次检查时间")),
                ("snapshot_data", models.JSONField(default=dict, verbose_name="实例快照数据")),
            ],
            options={
                "verbose_name": "订阅规则",
                "verbose_name_plural": "订阅规则",
                "db_table": "cmdb_subscription_rule",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization"], name="idx_sub_rule_org"),
                    models.Index(fields=["model_id"], name="idx_sub_rule_model"),
                    models.Index(fields=["is_enabled"], name="idx_sub_rule_enabled"),
                ],
            },
        ),
    ]
