# Generated by Django 4.2.7 on 2026-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0014_subscriptionrule"),
    ]

    operations = [
        migrations.RemoveField(model_name="collectmodels", name="examine",),
        migrations.AlterField(
            model_name="collectmodels",
            name="exec_status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "未执行"), (1, "正在采集"), (2, "成功"), (3, "异常"), (4, "超时"), (5, "正在写入"), (6, "强制终止")], default=0, help_text="执行状态"
            ),
        ),
    ]
