# Generated by Django 4.2.7 on 2026-03-27 09:08

from django.db import migrations, models


def update_cleanup_strategy_for_specific_models(apps, schema_editor):
    CollectModels = apps.get_model("cmdb", "CollectModels")
    target_model_ids = ["k8s_cluster", "vmware_vc", "aliyun_account", "qcloud"]
    CollectModels.objects.filter(model_id__in=target_model_ids).update(data_cleanup_strategy="immediately")


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0015_remove_collectmodels_examine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectmodels",
            name="data_cleanup_strategy",
            field=models.CharField(
                choices=[("no_cleanup", "不清理"), ("immediately", "及时清理"), ("after_expiration", "过期删除")],
                default="no_cleanup",
                help_text="数据清理策略",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="collectmodels",
            name="expire_days",
            field=models.PositiveSmallIntegerField(default=0, help_text="过期天数"),
        ),
        migrations.RunPython(update_cleanup_strategy_for_specific_models, migrations.RunPython.noop),
    ]
