# Generated by Django 4.2.22 on 2025-10-09 03:08

import apps.core.mixinx
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_cn', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(max_length=255)),
                ('is_build_in', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('enterprise_wechat', 'Enterprise Wechat'), ('enterprise_wechat_bot', 'Enterprise Wechat Bot')], max_length=30)),
                ('config', models.JSONField(default=dict)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, apps.core.mixinx.EncryptMixin),
        ),
        migrations.CreateModel(
            name='GroupDataRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_id', models.IntegerField(default=0)),
                ('group_name', models.CharField(max_length=100)),
                ('rules', models.JSONField(default=dict)),
                ('app', models.CharField(default='', max_length=50)),
            ],
            options={
                'unique_together': {('name', 'group_id', 'app')},
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('domain', models.CharField(default='domain.com', max_length=100)),
                ('group_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_mgmt.groupdatarule')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('disabled', models.BooleanField(default=False)),
                ('locale', models.CharField(default='zh-Hans', max_length=32)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=32)),
                ('group_list', models.JSONField(default=list)),
                ('role_list', models.JSONField(default=list)),
                ('temporary_pwd', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=128, null=True)),
                ('domain', models.CharField(default='domain.com', max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('username', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('app', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('menu_list', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('name', 'app')},
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('app', models.CharField(default='', max_length=50)),
                ('menu_type', models.CharField(default='', max_length=100)),
            ],
            options={
                'unique_together': {('name', 'app')},
            },
        ),
        migrations.CreateModel(
            name='LoginModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(default='wechat', max_length=50)),
                ('app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('app_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('other_config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('is_build_in', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'source_type')},
            },
            bases=(models.Model, apps.core.mixinx.EncryptMixin, apps.core.mixinx.PeriodicTaskUtils),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_id', models.IntegerField(default=0)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('name', 'parent_id')},
            },
        ),
    ]
