# Generated by Django 4.2.22 on 2025-10-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0012_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="roles",
            field=models.ManyToManyField(blank=True, to="system_mgmt.role", verbose_name="角色列表"),
        ),
    ]
