# Generated by Django 4.2.22 on 2025-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0013_group_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_virtual",
            field=models.BooleanField(default=False, verbose_name="是否虚拟组"),
        ),
    ]
