# Generated by Django 4.2.22 on 2025-10-29 09:00

from django.db import migrations


def create_default_virtual_group(apps, schema_editor):
    """创建默认的顶级虚拟组"""
    Group = apps.get_model("system_mgmt", "Group")

    # 检查是否已存在名为"虚拟组"的顶级组
    if not Group.objects.filter(name="虚拟团队", parent_id=0).exists():
        Group.objects.create(
            name="虚拟团队",
            parent_id=0,
            is_virtual=True,
            description="系统内置虚拟组，用于特殊用途的组织管理",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0014_group_is_virtual"),
    ]

    operations = [
        migrations.RunPython(
            create_default_virtual_group,
        ),
    ]
