# Generated by Django 4.2.22 on 2025-11-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0015_create_default_virtual_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("username", models.CharField(db_index=True, max_length=100, verbose_name="Username")),
                ("source_ip", models.GenericIPAddressField(db_index=True, verbose_name="Source IP")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        db_index=True,
                        default="success",
                        max_length=20,
                        verbose_name="Login Status",
                    ),
                ),
                ("domain", models.CharField(db_index=True, default="domain.com", max_length=100, verbose_name="Domain")),
                ("failure_reason", models.CharField(blank=True, default="", max_length=255, verbose_name="Failure Reason")),
                ("user_agent", models.CharField(blank=True, default="", max_length=500, verbose_name="User Agent")),
                ("os_info", models.CharField(blank=True, default="", max_length=100, verbose_name="Operating System")),
                ("browser_info", models.CharField(blank=True, default="", max_length=100, verbose_name="Browser")),
                ("location", models.CharField(blank=True, default="", max_length=200, verbose_name="Location")),
            ],
            options={
                "verbose_name": "User Login Log",
                "verbose_name_plural": "User Login Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at", "status"], name="system_mgmt_created_9d8154_idx"),
                    models.Index(fields=["username", "-created_at"], name="system_mgmt_usernam_40f655_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomMenuGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("display_name", models.CharField(max_length=100, verbose_name="显示名称")),
                ("app", models.CharField(max_length=50, verbose_name="所属应用")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                ("is_build_in", models.BooleanField(default=False, verbose_name="是否内置")),
                ("menus", models.JSONField(blank=True, default=list, verbose_name="菜单配置")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "自定义菜单组",
                "verbose_name_plural": "自定义菜单组",
                "db_table": "system_mgmt_custom_menu_group",
                "ordering": ["app", "id"],
                "indexes": [
                    models.Index(fields=["app"], name="system_mgmt_app_c928d8_idx"),
                    models.Index(fields=["app", "is_enabled"], name="system_mgmt_app_cf56de_idx"),
                ],
                "unique_together": {("app", "display_name")},
            },
        ),
    ]
