# Generated by Django 4.2.22 on 2025-11-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0016_userloginlog_custommenugroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("username", models.CharField(db_index=True, max_length=100, verbose_name="Username")),
                ("source_ip", models.GenericIPAddressField(db_index=True, verbose_name="Source IP")),
                ("app", models.CharField(db_index=True, max_length=100, verbose_name="Application")),
                (
                    "action_type",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete"), ("execute", "Execute")],
                        db_index=True,
                        max_length=20,
                        verbose_name="Action Type",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="", verbose_name="Summary")),
                ("domain", models.CharField(db_index=True, default="domain.com", max_length=100, verbose_name="Domain")),
            ],
            options={
                "verbose_name": "Operation Log",
                "verbose_name_plural": "Operation Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at", "action_type"], name="system_mgmt_created_bcc386_idx"),
                    models.Index(fields=["username", "-created_at"], name="system_mgmt_usernam_f966d1_idx"),
                    models.Index(fields=["app", "-created_at"], name="system_mgmt_app_2a131f_idx"),
                ],
            },
        ),
    ]
