# Generated by Django 4.2.22 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0020_user_account_locked_until_user_password_error_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="team",
            field=models.JSONField(default=list),
        ),
    ]
