# Generated by Django 4.2.22 on 2026-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0021_channel_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": "Maintainer Fields"},
        ),
        migrations.AddField(
            model_name="channel",
            name="created_by",
            field=models.CharField(default="", max_length=32, verbose_name="Creator"),
        ),
        migrations.AddField(
            model_name="channel",
            name="domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="Domain"),
        ),
        migrations.AddField(
            model_name="channel",
            name="updated_by",
            field=models.CharField(default="", max_length=32, verbose_name="Updater"),
        ),
        migrations.AddField(
            model_name="channel",
            name="updated_by_domain",
            field=models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain"),
        ),
    ]
