# Generated by Django 4.2.22 on 2026-02-05 07:00

from django.db import migrations


def update_empty_team_to_default(apps, schema_editor):
    """
    Update channels with empty team list to [1].
    """
    Channel = apps.get_model("system_mgmt", "Channel")
    Channel.objects.filter(team=[]).update(team=[1])


def reverse_update(apps, schema_editor):
    """
    Reverse: set team back to empty list where it equals [1].
    Note: This is a best-effort reverse, may affect manually set [1] values.
    """
    Channel = apps.get_model("system_mgmt", "Channel")
    Channel.objects.filter(team=[1]).update(team=[])


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0022_alter_channel_options_channel_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(update_empty_team_to_default, reverse_update),
    ]
