# Generated by Django 4.2.15 on 2025-11-08 03:54

import apps.core.fields.s3_json_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_policy_show_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrawdata',
            name='data',
            field=apps.core.fields.s3_json_field.S3JSONField(
                bucket_name='log-alert-raw-data',
                compressed=True,
                help_text='自动压缩并存储到 MinIO/S3',
                max_length=500,
                upload_to=apps.core.fields.s3_json_field.s3_json_upload_path,  # 修复：使用全局函数
                verbose_name='原始数据'
            ),
        ),
    ]
